### ISSUE TITLE
Brew formula fails to install

### ISSUE THREAD

**Issue by danirukun** [HolodexNet/holodex.js#2]
When trying to install the `holodex` formula, the following error occurs:
```
Installing holodex
==> Cloning https://github.com/holodata/dex.git
Updating /Users/***/Library/Caches/Homebrew/holodex--git
==> Checking out tag v0.1.0
HEAD is now at 596a64c v0.1.0
HEAD is now at 596a64c v0.1.0
==> npm install -ddd --build-from-source --cache=/Users/***/Library/Caches
Last 15 lines from /Users/***/Library/Logs/Homebrew/holodex/01.npm:
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/***/Library/Caches/Homebrew/npm_cache/eresolve-report.txt for a full report.
npm verb exit 1
npm timing npm Completed in 35217ms
npm verb unfinished npm timer reify 1636757355762
npm verb unfinished npm timer reify:loadTrees 1636757355765
npm verb unfinished npm timer idealTree:buildDeps 1636757355779
npm verb unfinished npm timer idealTree:node_modules/ts-jest 1636757390536
npm verb code 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/***/Library/Caches/Homebrew/npm_cache/_logs/2021-11-12T22_49_50_547Z-debug.log
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:60:in `issues_for_formula': undefined method `full_name' for nil:NilClass (NoMethodError)
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:489:in `fetch_issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:485:in `issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:539:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:155:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:143:in `<main>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2297:in `block in system': Failed executing: npm install -ddd --build-from-source --cache=/Users/danpetrov/Library/Caches/Homebrew/npm_cache (BuildError)
	from /usr/local/Homebrew/Library/Homebrew/formula.rb:2233:in `open'
	from /usr/local/Homebrew/Library/Homebrew/formula.rb:2233:in `system'
	from /usr/local/Homebrew/Library/Taps/sake.sh/homebrew-holodata/holodex.rb:20:in `install'
	from /usr/local/Homebrew/Library/Homebrew/build.rb:172:in `block (3 levels) in install'
	from /usr/local/Homebrew/Library/Homebrew/utils.rb:550:in `with_env'
	from /usr/local/Homebrew/Library/Homebrew/build.rb:134:in `block (2 levels) in install'
	from /usr/local/Homebrew/Library/Homebrew/formula.rb:1291:in `block in brew'
	from /usr/local/Homebrew/Library/Homebrew/formula.rb:2463:in `block (2 levels) in stage'
	from /usr/local/Homebrew/Library/Homebrew/utils.rb:550:in `with_env'
	from /usr/local/Homebrew/Library/Homebrew/formula.rb:2462:in `block in stage'
	from /usr/local/Homebrew/Library/Homebrew/resource.rb:126:in `block (2 levels) in unpack'
	from /usr/local/Homebrew/Library/Homebrew/download_strategy.rb:110:in `chdir'
	from /usr/local/Homebrew/Library/Homebrew/download_strategy.rb:102:in `stage'
	from /usr/local/Homebrew/Library/Homebrew/resource.rb:122:in `block in unpack'
	from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
	from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
	from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `run'
	from /usr/local/Homebrew/Library/Homebrew/resource.rb:208:in `mktemp'
	from /usr/local/Homebrew/Library/Homebrew/resource.rb:121:in `unpack'
	from /usr/local/Homebrew/Library/Homebrew/resource.rb:96:in `stage'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
	from /usr/local/Homebrew/Library/Homebrew/formula.rb:2442:in `stage'
	from /usr/local/Homebrew/Library/Homebrew/formula.rb:1284:in `brew'
	from /usr/local/Homebrew/Library/Homebrew/build.rb:129:in `block in install'
	from /usr/local/Homebrew/Library/Homebrew/utils.rb:550:in `with_env'
	from /usr/local/Homebrew/Library/Homebrew/build.rb:124:in `install'
	from /usr/local/Homebrew/Library/Homebrew/build.rb:224:in `<main>'
```

Node: v17.0.1
macOS 12.0.1 21A559 x86_64

**Comment by stu43005** [comment]
Sorry for the late reply

This Homebrew package is different project: https://github.com/holodata/dex

holodex.js cli can be installed by running `npm install -g holodex.js`
